### ISSUE TITLE
Sobre parseo de lotes e importes

### ISSUE THREAD

**Issue by moon155** [Ingobernable/kaos155#12]
Hola!

1. como contabilizais cuando solo disponemos del total adjudicado,
mientras son varias empresas las contratistas? Como en este caso:

![screenshot from 2017-11-22 18-57-08](https://user-images.githubusercontent.com/32641121/33152811-f3cc43a0-cfde-11e7-8e45-0cc634c7fcc6.png)

2. si no hay ningun "Importe o canon de adjudicación" especificado, cogeis el "Valor estimado del contrato"? El presupuesto base de licitación? (nos sirven de algo estas 2 cosas?)

3. como lo contabilizais cuando el importe esta del tipo "0.06
euro/palabra"??

4. almacenais importes totales o netos? (o ambos..?)

5. podeis darme un doc o algo con las fechas chungas que teneis sobre
boe y borme? (importante!)

Gracias!

**Comment by torbellina** [comment]
Alex, todavía no hemos analizado bien lo de los importes.  En cuanto sepa algo te digo, lo mismo te enteras tú antes. :P

**Comment by moon155** [comment]
Propongo:
1. dos soluciones que veo para aquellos casos:
- atribuimos la parte proporcional del botín a cada empresa, o
- atribuimos (almacenamos) rangos de botín: "Empresa X obtuvó entre 0 y YYY€"
2. cojamos "el valor estimado del contrato" (como tal), por tener algo..
3. lo contabilizamos como 0,06€ de momento..
4. solo totales, pero netos si no hay totales (aplicamos alguna iva medio?)
5. es importante, necesito probar con fechas chungas (no años, fechas), a ver si parsea bien los lotes!!! 

Pregunto tanto sobre importes porque me habia parecido que queríamos obtener sumas exactas.. pero será en los lotes, no es los patrones ;Þ

**Comment by moon155** [comment]
Y dejo capturitas de recuerdo

**Comment by Softman65** [comment]
En cuanto a los importes, en los contratos modernos, desde 2015 tenemos un campo importe del contrato en los metadatos, si no es lote y tenemos ese, ese vale, en otros casos casos manda importe, si importe falla, mas arriba hay un importe del contrato (tener en cuenta solo en ultimo caso)

en cuanto a los lotes componemos una array con los contratistas y los importes netos, cada elemento despliega un registro contrato, salvo en el caso de las UTE (unión temporal de empresas), que entonces genera un solo contrato con un solo importe aunque en la UTE sean n empresas.

un pequeño detalle, los acronimos Sociedad anónima, Sociedad Limitada, Union Temporal de Empresas etc...... los transformamos en SA SL UTE sin signos de puntuación, importante para que luego casen las empresas con las obtenidas del BORME que es el que marca la pauta real acerca de como se llama la empresa.

EN CUANTO a fechas chungas 
[boe 2016-2017 dificiles.zip](https://github.com/Ingobernable/kaos155/files/1500385/boe.2016-2017.dificiles.zip)

buenas lunas

**Comment by moon155** [comment]
Hola Softman!
No entiendo todo pero lo hablaremos más en detalles en un futuro próximo supongo ;)

Sobre SA, SL, .. también las almaceno como dices, pero detecto cualquier empresa desde cero, siempre, sin usar datos ya en BBDD.. ;)

Sobre fechas chungas, gracias, voy a investigar este JSON! Aunque con fecha+empresa me resultaria más fácil..... 

6. Y dejo unas pocas fechas problemáticas que he detectado para el BORME. Coincide con las vuestras???

![screenshot from 2017-11-24 15-31-02](https://user-images.githubusercontent.com/32641121/33214846-da129ed2-d12d-11e7-959c-268943ab74c6.png)

![screenshot from 2017-11-24 15-34-23](https://user-images.githubusercontent.com/32641121/33214849-dc81dd54-d12d-11e7-8836-59dd4c46fd76.png)

Gracias!

**Comment by moon155** [comment]
Por cierto, estos errores de mi punto 6. son errores sobre recogida de BORMEs, no sobre parseo!!

**Comment by moon155** [comment]
6. Ah bueno, los errores se han solucionado solos :)) Probablemente errores de conexión..

![screenshot from 2017-11-24 18-27-43](https://user-images.githubusercontent.com/32641121/33219907-47085628-d145-11e7-9001-e1117d4e669e.png)

**Comment by Softman65** [comment]
moon155 abre un fork para que podamos participar todos, pero no a base de pantallazos. Lo siento pero ya sabes cuál es la filosofía de kaos155, código libre.

**Comment by moon155** [comment]
Claro claro, salvo que yo no pienso publicar tantos esfuerzos bajo licencia lorem corpus, que desprotegería todo... así que vais a tener q esperar un poquito más a que me aclare con las licencias. Gracias
