### ISSUE TITLE
Licencia elegida, y licencia de SM

### ISSUE THREAD

**Issue by moon155** [Ingobernable/kaos155#13]
Hola!

1. Me pregunto porque permiteis el uso comercial de Kaos?

2. Y también me pregunto si no usar Creative Commons para SM, contestando NO-NO o ALIKE-NO a este cuestionario: https://creativecommons.org/choose/ Veis algo peligroso en hacerlo? (uso futuro por periodistas y más, posible sostenibilidad económica del proyecto por ejemplo..)

Gracias!

**Comment by Softman65** [comment]
estamos preparando la autentica licencia. de momento esta en maori, podria ser una pasada.

Ehara te Kaporeihana Creative Commons ("Creative Commons") i te umanga ture, kāore hoki e whakarato ana i ngā ratonga ture, ngā tohutohu ture rānei. Kāore e waihangatia ana e te tohatohanga o ngā raihana tūmatanui Creative Commons tētahi whanaungatanga rōia-kiritaki, tētahi atu whanaungatanga rānei. E whakawātea ana a Creative Commons i ōna raihana me ngā mōhiohio whai pānga i runga i "tāu e kite ana, koia". Kāore a Creative Commons e whakarato pūtāhui ana e pā ana ki ōna raihana, ki ngā rawa e raihanatia ana i raro i ōna ture me ōna here, me ētahi atu mōhiohio whai pānga rānei. E tino karohia rawa atu ana e Creative Commons ngā taunaha katoa mō ngā rarunga ka puta i te whakamahinga o ēnei raihana.

Te Whakamahi Raihana Tūmatanui Creative Commons

E whakarato ana ngā raihana tūmatanui Creative Commons i te huinga noa o ngā ture me ngā herenga ka āhei ngā kaihanga me ērā atu kaipupuri motika te whakamahi pea ki te tiritiri i ngā rawa taketake me ētahi atu rawa kei raro i te manatārua, me ētahi atu motika e tautuhia ana i te raihana tūmatanui i raro. He mea whakamōhiohio anake ngā whakaarohanga e whai ake ana, ehara i te ngaio, kāore hoki e whai wāhi ki ā mātou raihana.

Ngā whakaarohanga mō ngā kaituku raihana: Kua hoahoatia ā mātou raihana mā te hunga kua whakamanahia ki te tuku whakaaetanga tūmatanui mō te whakamahi rawa mā nga tikanga e rāhui kētia ana e te manatārua, e ētahi atu motika rānei. Kāore e taea te whakakore i ā mātou raihana. Me panui, me mārama anō hoki ngā kaituku raihana ki ngā ture me ngā herenga o te raihana e kōwhiri ana rātou i mua i te whakamahi. Me whakananawe ngā kaituku raihana i ngā motika katoa e hiahiatia ana i mua i te whakahāngai i ō mātou raihana kia taea ai e te iwi whānui te whakamahi anō ngā rawa mā ngā ara e tūmanakohia ana. Me tautohu mārika ngā kaituku raihana i ngā rawa kāore e herea e te raihana. Kei roto i ēnei ērā atu rawa kua raihanatia mā Creative Commons, ngā rawa rānei e whakamahia ana i runga anō i te aweretanga, herenga rānei ki te manatārua. Ētahi whakaarohanga anō mō ngā kaituku raihana.
Ngā whakaarohanga mō te iwi whānui: Mā te whakamahi i tētahi o ā mātou raihana tūmatanui ka tuku whakaaetanga te kaituku raihana ki te iwi whānui ki te whakamahi i ngā rawa kua raihanatia i raro i ngā ture me ngā herenga kua tautuhia. Mēnā kāore e hiahiatia te whakaaetanga a te kaituku raihana ahakoa te take – hei tauira, nā tētahi aweretanga, herenga rānei ki te manatārua – kāore i te tauherea taua whakamahinga e te raihana. Ka tuku anake ā mātou raihana i ngā whakaaetanga i raro i te manatārua, me ētahi atu motika kei te kaituku raihana te mana tuku. Tērā pea ka herea tonutia te whakamahinga o ngā rawa kua raihanatia nā ētahi atu pūtake, tae atu ki te mea he manatārua, he motika atu anō ō ētahi atu tāngata ki ngā rawa. Ka waihanga pea te kaituku raihana i ētahi tono motuhake, hei tauira, te tono kia tohua, kia whakaahuatia rānei ngā panoni katoa. Ahakoa kāore i te hiahiatia e ō mātou raihana, ka whakatītinatia koe ki te whakaute i aua tono ina tika tēnā. Ētahi whakaarohanga anō mō te iwi whānui.
Raihana Tūmatanui ā-Ao Tautohu Matatiki-Arumoni Kore-Taketake Anake Creative Commons 4.0

Mā te whakamahi i Ngā Motika Kua Raihanatia (he mea tautuhi i raro nei), ka whakaae Koe kia herea e ngā ture me ngā herenga o tēnei Raihana Tūmatanui ā-Ao Tautohu Matatiki-Arumoni Kore-Taketake Anake Creative Commons 4.0 ("Raihana Tūmatanui"). Ki te whanuitanga e whakaarohia ai tēnei Raihana Tūmatanui hei kirimana, ka tukuna ki a Koe Ngā Motika Kua Raihanatia i runga i Tō whakaaetanga ki ēnei ture me ngā herenga, ā, ka tuku te Kaituku Raihana ki a Koe aua motika i runga anō i ngā huanga e whiwhi te Kaituku Raihana mō tāna whakawātea i Ngā Rawa Kua Raihanatia i raro i aua ture me ngā herenga.

Wāhanga 1 – Ngā Whakamāramatanga.

Ko te tikanga o Ngā Rawa Kua Urutaua ko ērā rawa kei raro i te Manatārua me ngā Motika Rite he mea ahu mai i Ngā Rawa Kua Raihanatia, ko aua rawa rānei te pūtake, ā, he mea whakamāori, whakarerekē, whakaraupapa, panoni, huri kē rānei aua Rawa Kua Raihanatia mā te āhua e hiahiatia ai te whakaaetanga i raro i te Manatārua me ngā Motika Rite e puritia ana e te Kaituku Raihana. Mō te pūtake o tēnei Raihana Tūmatanui, e noho ai te Rawa Kua Raihanatia he mahi puoro, he whakakitenga, he hopukanga oro rānei, e whakaputaina ana Ngā Rawa Kua Urutaua i ngā wā katoa e tukutahi tahitia ai aua Rawa Kua Raihanatia ki tētahi atahanga nekeneke.
Ko te tikanga o te Manatārua me ngā Motika Rite ko ngā motika manatārua, ngā motika rite hoki/rānei e tino pātata ana ki te manatārua, tae atu, me te kore herenga, ki te whakakitenga, te whakapāho, te hopukanga oro, me ngā Motika Pātengi Raraunga Momo Takitahi, me te kore aro ki te āhua e waitohua ai, e whakarōpūhia ai rānei aua motika. Mō ngā pūtake o tēnei Raihana Tūmatanui, ehara ngā motika he mea tautuhi i te Wāhanga 2(b)(1)-(2) i te Manatārua me Ngā Motika Rite.
Ko te tikanga o Ngā Tikanga Hangarau Tōtika ko ērā tikanga e kore rawa e taea, ina ngaro tētahi mana tika, te karo i raro i ngā ture whakatutuki herenga kei te Upoko 11 o te WIPO Copyright Treaty i whakamanaia i te 20 o Hakihea, 1996, i ētahi atu whakaaetanga ā-ao rite hoki/rānei.
Ko te tikanga o Ngā Aweretanga me ngā Whāititanga ko te whakamahi me te whakarite i runga i te tōkeke, ko tētahi atu aweretanga hoki/rānei, whāititanga rānei ki te Manatārua me Ngā Motika Rite e hāngai ana ki Tō whakamahi i Ngā Rawa Kua Raihanatia.
Ko te tikanga o Ngā Rawa Kua Raihanatia ko te mahi toi, mahi tuhinga rānei, te pātengi raraunga, ētahi atu rawa rānei i hoatu ai e te Kaituku Raihana ki tēnei Raihana Tūmatanui.
Ko te tikanga o Ngā Motika Kua Raihanatia ko ngā motika i tukuna ki a Koe i runga anō i ngā ture me ngā herenga o te Raihana Tūmatanui, e whāiti ana ki te katoa o te Manatārua me Ngā Motika Rite e hāngai ana ki Tō whakamahi i Ngā Rawa Kua Raihanatia, ā, kei te Kaituku Raihana te mana tuku raihana.
Ko te tikanga o te Kaituku Raihana ko te tangata, ngā tāngata, te/ngā hinonga rānei e tuku motika ana i raro i tēnei Raihana Tūmatanui.
Ko te tikanga o te Arumoni Kore kāore e āta hangaia ana hei whiwhi painga arumoni, whiwhi paremata ā-moni rānei. Mō ngā pūtake o tēnei Raihana Tūmatanui, he Arumoni Kore te whakawhitinga o Ngā Rawa Kua Raihanatia mō ētahi atu rawa kei raro i te Manatārua me Ngā Motika Rite mā te Tiritiri kōnae matihiko, mā tētahi atu ara rite rānei, engari rā mēnā kāore he utu paremata ā-moni e pā ana ki te whakawhitinga.
Ko te tikanga o te Tiritiri ko te whakarato rawa ki te iwi whānui mā te katoa o ngā ara, tukanga rānei e hiahia whakaaetanga ana i raro i Ngā Motika Kua Raihanatia, pēnei i te tāruarua, te whakaaturanga tūmatanui, te whakakitenga tūmatanui, te tohatoha, te whakahōrapa, te whakawhitiwhiti, te kawe mai, me te whakawātea i ngā rawa ki te iwi whānui mā ngā ara hoki e āhei ai te iwi whānui te uru ki aua rawa ahakoa te wāhi, te wā rānei e kowhiri ana rātou.
Ko te tikanga o Ngā Motika Pātengi Raraunga Momo Takitahi ko ngā motika hāunga te manatārua ka puta i te Whakaritenga 96/9/EC o te Pāremata Uropi me te Kaunihera o te 11 o Poutūterangi 1996 mō te parenga ā-ture o ngā pātengi raraunga, ahakoa kua whakatikahia, kua whakakapia hoki/rānei, me ērā atu motika ōrite anō hoki ahakoa kei hea i te ao.
Ko te tikanga o tūpou Koe ko te tangata, te hinonga rānei e tuku ana i Ngā Motika Kua Raihanatia i raro i tēnei Raihana Tūmatanui. He tikanga hāngai tō te kupu Tō.
Wāhanga 2 – Te Whānuitanga.

Te tuku raihana.
I runga anō i ngā ture me ngā herenga o tēnei Raihana Tūmatanui, ka tuku te Kaituku Raihana ki a Koe i tētahi raihana puta noa i te ao, kāore he utu raihana, e kore ai e āhei te tuku ki tangata kē, ehara i te motuhake, e kore ai e taea te whakakore, mō te whakamahi i Ngā Motika Kua Raihanatia i roto i Ngā Rawa Kua Raihanatia ki te:
tāruarua me te Tiritiri i te katoa, i te wāhi rānei o Ngā Rawa Kua Raihanatia, mō ngā pūtake Arumoni Kore anake; me te
whakanao, te tāruarua, engari kaua e Tiritiri i Ngā Rawa Kua Urutaua mō ngā pūtake Arumoni Kore anake.
Ngā Aweretanga me ngā Whāititanga. Hei karo i te rangirua, i ngā wahi kei reira he Aweretanga me ngā Whāititanga ki Tō whakamahi, kāore e hāngai ana tēnei Raihana Tūmatanui, ā, kāore koe e mate ki te tautuku ki ōna ture me ōna herenga.
Te Roanga. E tautuhia ana te roanga mō tēnei Raihana Tūmatanui i te wāhanga 6(a).
Ngā rawatā me ngā hōputu; ka whakaaetia ngā whakarerekētanga hangarau. Ka tuku te Kaituku Raihana i te mana ki a Koe ki te whakamahi i Ngā Motika Kua Raihanatia i roto i ngā rawatā katoa me ngā hōputu katoa, ahakoa kua mōhiotia ināianei, ahakoa ka hangaia ā muri atu rānei, ki te hanga hoki i ngā whakarerekētanga hangarau e hiahiatia ana hei whakamahi i aua motika. Ka whakakore te Kaituku Raihana, ka whakaae hoki/rānei kia kaua ia e whakapuaki i tētahi motika, mana rānei ki te whakakore i Tō hanga whakarerekētanga hangarau e hiahiatia ana ki te whakamahi i Ngā Motika Kua Raihanatia, tae atu ki ngā whakarerekētanga hangarau e hiahiatia ana ki te karo i Ngā Tikanga Hangarau Tōtika. Mō ngā pūtake o tēnei Raihana Tūmatanui, e kore rawa te hanga whakarerekētanga noa iho kua whakamanaia e tēnei Wāhanga 2(a)(4) e whakaputa i Ngā Rawa Kua Urutaua.
Ngā kaiwhiwhi o muri.
He tukunga mai i te Kaituku Raihana – Ngā Rawa Kua Raihanatia. Ka whiwhi aunoa ia kaiwhiwhi o Ngā Rawa Kua Raihanatia i te tukunga mai i te Kaituku Raihana ki te whakamahi i Ngā Motika Kua Raihanatia i runga anō i ngā ture me ngā herenga o tēnei Raihana Tūmatanui.
Kāore he whāititanga ki ngā kaiwhiwhi o muri. Kāore koe e āhei te tuku, te uta rānei i ngā ture me ngā herenga tāpiri, rerekē rānei, te hoatu i ētahi Tikanga Hangarau Tōtika, ki Ngā Rawa Kua Raihanatia, mēnā mā te pēnā ka whakatikia te whakamahinga o Ngā Motika Kua Raihanatia e tētahi kaiwhiwhi o Ngā Rawa Kua Raihanatia.
Kāore he tautokonga. Ehara tētahi mea i roto i tēnei Raihana Tūmatanui i te whakaaetanga, kia kaua e whakaarohia rānei hei whakaaetanga, ki te kī, ki te whakapae rānei, ko Koe, ko Tō whakamahi rānei i Ngā Rawa Kua Raihanatia, e hono ana ki te Kaituku Raihana, e tautokona ana, e whakamanaia ana, kua whakawhiwhia ki te tūnga whaimana rānei e ia, e ētahi atu rānei he mea tautuhi kia whiwhi i te tautohu matatiki mā te tikanga kei roto i te Wāhanga 3(a)(1)(A)(i).
Ērā atu mōtika.

Kāore ngā motika matatika, pēnei i te motika ngākau tapatahi, kāore hoki te whakaaturanga, te punanga, ētahi atu motika whaiaro rite hoki/rānei, i te raihanatia i raro i tēnei Raihana Tūmatanui; heoi, ka tino whakakore rawa atu te Kaituku Raihana, ka whakaae hoki/rānei kia kaua e whakapuaki i ngā motika pēnei e puritia ana e te Kaituku Raihana ki te whānuitanga anake e hiahiatia kia tukuna Koe ki te whakamahi i Ngā Motika Kua Raihanatia, engari kia kaua i tua atu.
Kāore ngā motika whakamana ā-ture me ngā motika moko i te raihanatia i raro i tēnei Raihana Tūmatanui.
Ki te whānuitanga ka taea, e whakakore ana te Kaituku Raihana i ngā motika ki te kohi utu raihana i a Koe mō te whakamahi i Ngā Motika Kua Raihanatia, ahakoa mā te ara tika atu, ahakoa mā tētahi rōpū kohi i raro i tētahi kaupapa tūao, kaupapa ā-ture ka taea te whakakore, kaupapa raihanatanga whakature rānei. I ērā atu āhuatanga katoa ka āta rāhui te Kaituku Raihana i ngā motika ki te kohikohi i ngā utu motika pēnei, tae atu ki ngā wā e whakamahia ana Ngā Rawa Kua Raihanatia mō ngā pūtake Arumoni Kore.
Wāhanga 3 – Ngā Herenga Raihana.

Ka āhei Koe te whakamahi i Ngā Motika Kua Raihanatia e ai ki ēnei herenga.

Te Tautohu Matatiki.

Mēnā ka Tiritiri Koe i Ngā Rawa Kua Raihanatia, me mahi rawa Koe i ēnei:

me pupuri rawa i ēnei mēnā kua whakaratohia e te Kaituku Raihana i te taha o Ngā Rawa Kua Raihanatia:
te tuakiri o te/ngā kaihanga o Ngā Rawa Kua Raihanatia me ērā atu kua tohua kia whiwhi i te tautohu matatiki, ahakoa te momo whaitake, e tonoa ana e te Kaituku Raihana (mā te ingoa kē anō hoki mēnā kua tohua kia pērā);
tētahi pānui manatārua;
tētahi pānui e kōrerotia ai tēnei Pānui Tūmatanui;
tētahi pānui e kōrerotia ai te karo pūtāhui;
tētahi URL, honongaitua rānei ki Ngā Rawa Kua Raihanatia ki te whānuitanga ka taea;
me whakaatu rawa mēnā i whakarerekē Koe i Ngā Rawa Kua Raihanatia me te pupuri whakaaturanga o ngā whakarerekētanga o mua atu; ā,
me whakaatu rawa kua raihanatia Ngā Rawa Kua Raihanatia i raro o tēnei Raihana Tūmatanui, me te tāuru i ngā kuputuhi o tēnei Raihana Tūmatanui, te URL, te honongaitua rānei ki taua raihana.
Hei karo i te rangirua, kāore Koe e whakaaetia ana i raro i tēnei Raihana Tūmatanui ki te Tiritiri i Ngā Rawa Kua Urutaua.
Ka āhei koe te whakatutuki i ngā herenga i te Wāhanga 3(a)(1) ahakoa he aha te ara whaitake, i runga anō i te rawatā, te āhua, me te horopaki e tiria ai e Koe Ngā Rawa Kua Raihanatia. Hei tauira, he mea whaitake pea te whakatutuki i ngā herenga mā te whakarato i tētahi URL, honongaitua rānei ki tētahi rauemi kei roto ko ngā mōhiohio e hiahiatia ana.
Mēnā ka tonoa e te Kaituku Raihana, me tango rawa e Koe ngā mōhiohio e hiahiatia ana e te Wāhanga 3(a)(1)(A) ki te whānuitanga ka taea.
Wāhanga 4 – Ngā Motika Pātengi Raraunga Momo Takitahi.

Ina kei roto i Ngā Motika Kua Raihanatia ko Ngā Motika Pātengi Raraunga Momo Takitahi e hāngai ana ki Tō whakamahi i Ngā Rawa Kua Raihanatia:

hei karo i te rangirua, ka tuku te Wāhanga 2(a)(1) i te motika ki a Koe ki te tango, te whakamahi anō, te tāruarua, me te Tiritiri i te katoa, tētahi wāhi nui rānei o ngā ihirangi o te pātengi raraunga, mō ngā pūtake Arumoni Kore anake, engari rā mēnā kāore Koe e Tiritiri i Ngā Rawa Kua Urutaua;
mēnā ka whakauru Koe i te katoa, i tētahi wāhi nui rānei o ngā ihirangi pātengi raraunga ki roto i tētahi pātengi raraunga e whai Motika Pātengi Raraunga Momo Takitahi ai Koe, ka mutu ko taua pātengi raraunga e whai Motika Pātengi Raraunga Momo Takitahi ai Koe (engari kaua ōna ihirangi) he Rawa Kua Urutaua; ā,
me tautuku Koe ki ngā herenga i te Wāhanga 3(a) mēnā ka Tiritiri Koe i te katoa, i tētahi wāhi nui rānei o ngā ihirangi o te pātengi raraunga.
Hei karo i te rangirua, ka āpiti tēnei Wāhanga 4 me te kore e whakakapi i Ō herenga i raro i tēnei Raihana Tūmatanui i ngā āhuatanga kei roto i Ngā Motika Kua Raihanatia ētahi atu Motika Manatārua, Motika Rite hoki.
Wāhanga 5 – Te Karo Pūtāhui me te Whakawhāiti Taunahatanga.

Ka tuku te Kaituku Raihana, engari rawa mēnā ka whakahaeretia motuhaketia e te Kaituku Raihana, ki te whānuitanga ka taea, i Ngā Rawa Kua Raihanatia ki tōna āhua tonu, mēnā ka wātea i taua wā, ā, kāore ia e tuku kī taurangi, pūtāhui ahakoa te momo mō Ngā Rawa Kua Raihanatia, ahakoa mā te kī mārama, mā te whakapae, mā te ture, mā tētahi atu āhua rānei. Kei roto i tēnei, me te kore herenga, ngā pūtāhui taitara, te pai hei hoko, te rite mō tētahi kaupapa ake, te kore takahitanga, te korenga o ngā makenu torohū, o ētahi atu makenu rānei, te tōtikatanga, te whai hapa, te kore whai hapa rānei, ahakoa ka mōhiotia, kāore rānei, ahakoa ka kitea ā tōna wā, kāore rānei. I ngā āhuatanga kāore e whakaaetia ngā karo pūtāhui katoa, tētahi wāhi rānei, kāore pea tēnei karo e hāngai ki a Koe.
Ki te whānuitanga ka taea, ahakoa te āhuatanga, e kore te Kaituku Raihana e herea ki a Koe i raro i tetahi ariā ā-ture (tae atu, me te kore herenga, ki te whakahapanga), i raro i tētahi atu mea rānei, mō ngā moni ngaro torotika, motuhake, ka hua ake, whakawhiu, whakatūpato, tētahi atu moni ngaro rānei, mō ngā utunga, ngā rarunga rānei ka hua ake i tēnei Raihana Tūmatanui, i te whakamahinga rānei o Ngā Rawa Kua Raihanatia, ahakoa kua whakamōhiotia te Kaituku Raihana tērā pea ka tūpono ngā moni ngaro, ngā utunga, ngā rarunga pēnei rānei. I ngā āhuatanga kāore e whakaaetia ngā karo pūtāhui katoa, tētahi wāhi rānei, kāore pea tēnei karo e hāngai ki a Koe.
Kia whakamāoritia tēnei karo pūtāhui me te whakawhāititanga o te taunahatanga e whakaratohia ana i runga nei kia tino pātata rawa ka taea tōna āwhiwhi ki tētahi karo, whakakore pūmau o te taunahatanga katoa.
Wāhanga 6 – Te Roanga me te Whakamutu.

E hāngai ana tēnei Raihana Tūmatanui mō te roanga o te Manatārua me ngā Motika Rite kua raihanatia i konei. Heoi anō, ki te kore Koe e tautuku ki tēnei Raihana Tūmatanui, ka mutu aunoa Ō motika i raro i tēnei Raihana Tūmatanui.
I ngā āhuatanga i whakamutua aunoatia Tō motika ki te whakamahi i Ngā Rawa Kua Raihanatia i raro i te Wāhanga 6(a):

ka whakatūria aunoatia anō hei te rā whakatika i te takahitanga, engari rā ka whakatikahia i roto i te 30 rā atu i Tō kite i te takahitanga; tēnei rānei,
ka āta whakatūria anō e te Kaituku Raihana.
Hei karo i te rangirua, kāore he pānga o tēnei Wāhanga 6(b) ki tō te Kaituku Raihana motika ki te rapa rongoā mō Ō takahitanga o tēnei Raihana Tūmatanui.
Hei karo anō i te rangirua, ka tuku pea te Kaituku Raihana i Ngā Rawa Kua Raihanatia i raro i ngā ture me ngā herenga rerekē, ka whakamutu rānei i te tohatoha o Ngā Rawa Kua Raihanatia i ngā wā katoa; heoi, mā te pērā e kore e poroa tēnei Raihana Tūmatanui.
Ka ora tonu ngā Wāhanga 1, 5, 6, 7, me te 8 i te whakamutunga o tēnei Raihana Tūmatanui.
Wāhanga 7 – Te Roanga me te Whakamutu.

Kāore e herea te Kaituku Raihana ki ētahi anō ture rerekē, herenga rerekē rānei e kōrerotia ana e Koe engari ia kua āta whakaaetia ērā.
E noho wehewehe ana, e noho motuhake ana ngā whakaritenga, whakaaetanga rānei e pā ana ki Ngā Rawa Kua Raihanatia kāore i te kōrerotia i roto nei, i ngā ture me ngā herenga o tēnei Raihana Tūmatanui.
Wāhanga 8 – Te Whakamāoritanga.

Hei karo i te rangirua, kia kaua tēnei Raihana Tūmatanui e whakamāoritia ki te whakaiti, whakawhāiti, whakatiki, uta rānei i ngā herenga ki te whakamahinga o Ngā Rawa Kua Raihanatia tērā ka whakamahia ā-turetia me te kore whakaaetanga i raro i tēnei Raihana Tūmatanui.
Ki te whānuitanga ka taea, mēnā ka meinga e kore e taea te uruhi tētahi whakaratonga o tēnei Raihana Tūmatanui, ka whakahou aunoatia ki te iti rawa ka taea ki te whakarite ka taea te uruhi. Ki te kore e taea te whakaratonga te whakahou, ka motuhia i tēnei Raihana Tūmatanui me te kore whai pānga ki te uruhinga o ngā ture me ngā herenga e toe ana.
E kore e whakakorea tētahi herenga o tēnei Raihana Tūmatanui, e kore hoki e whakaaetia tētahi hapa tautuku engari ia ka āta whakaaetia e te Kaituku Raihana.
Kāore tētahi mea i roto i tēnei Raihana Tūmatanui e here, e whakakore, e kitea ana rānei ki te here, ki te whakakore rānei, i ngā painga me ngā āraitanga e hāngai ana ki te Kaituku Raihana, ki a Koe rānei, tae atu ki ērā e ahu mai ana i ngā tukanga ā-ture o tētahi rohe ture, tētahi mana rānei.

**Comment by moon155** [comment]
.... y que opinais sobre las dos preguntas del enlace de mi punto 2.? (que son las dos cosas más importantes a nivel jurídico, me parece)

**Comment by ghost** [comment]
Las licencias creative commons a nivel general no son la mayoría licencias consideradas libres.
La mayoría de ellas no lo son y a nivel general se suelen utilizar para "contenidos": Una canción, un libro, un documental, ...

La licencia que tiene kaos155 es una licencia libre. La GPL 3. Una licencia pensada para el software, pensada para software libre.

**Comment by ghost** [comment]
La GPL 3 permite:

- **Usarse con fines comerciales.** Por ejemplo mucha gente usa inkscape para desarrollar sus trabajos con fines comerciales (un logo, un cartel, ...) y la licencia de la herramienta no les prohibe hacerlo de esa forma. Lo mismo con el resto de herramientas GNU que usamos. Tampoco les prohibe empaquetar inkscape y venderlo. Pero la licencia pone unas condiciones.
Si no se permite esto deja de ser una licencia de las que se consideran "libres" en cuanto a software.

**Modificarlo.** Puedes usar este software y modificarlo a tu gusto. Por ese motivo se hace libre para que otros puedan ver sus entrañas pero al mismo tiempo tambien modificarlas. Con las respectivas condiciones de que entre otras cosas si lo hacen están obligados a hacerlo en los mismos terminos y condiciones de la licencia. Es decir, **tienen que liberar el código si modifican kaos155**. De esa forma todos/as ganamos y han de hacerlo en las mismas condiciones. Si no lo hacen así pueden ser denunciados por kaos155 y ganaría kaos155 posiblemente si las modificaciones se están vendiendo con otra licencia copyright privativa por ejemplo. (existen bastantes sentencias en españa que han legitimado las licencias de software libre en este aspecto).

**Distribuirlo.** Puedes distribuir kaos155 en cd, un pendrive, en lo que te de la gana. Pero has de cumplir con ciertas condiciones. No puedes atribuirte la autoria por ejemplo y has de liberarlo bajo los mismo terminos de la licencia. Esto permite que cualquiera pueda enviarle a otra persona una copia de kaos155. Compartir es bueno.

De modo que si alguien quiere hacer un fork de Kaos155 es libre de hacerlo pero ha de compartir el código bajo los mismos terminos. Si no lo hace así podría ser denunciado perfectamente.

**Comment by moon155** [comment]
Gracias por tus aclaraciones Fanta! Te remito a mi respuesta ahí: https://github.com/Ingobernable/kaos155/issues/16
