### ISSUE TITLE
Abrir wiki de GitHub

### ISSUE THREAD

**Issue by j-lml** [Ingobernable/kaos155#14]
La wiki nos puede servir para ir dejando las notas que queramos del proyecto.

**Comment by j-lml** [comment]
Cuando está creada se puede gestionar como si fuera un subproyecto de git.

     git clone https://github.com/ingobernable/kaos155.wiki.git

y se suben los cambios que se hagan desde fuera como pull-request.

**Comment by torbellina** [comment]
sí, ayer estuve echando un vistazo y le pasé esto a Ricardo, precisamente por lo de la wiki. Me gustó.
https://github.com/BigNeuron/BigNeuron-Wiki/wiki

**Comment by ghost** [comment]
https://github.com/Ingobernable/kaos155/wiki  wiki abierta.
