### ISSUE TITLE
Elegir la BBDD adecuada

### ISSUE THREAD

**Issue by moon155** [Ingobernable/kaos155#15]
De momento usamos MySQL pero se esta preparando pasar a ElasticSearch (ES).

1. A mi me preocupa que ES no sea ACID-compliant, he leido mucha gente usando MySQL como BBDD principal y ES como motor de busqueda (FULL TEXT).

2. Conoceis Percona y TokuDB? Dicen que permite aumentar la velocidad de MySQL por un orden de 10 a 100, manteniendo todo ACID-compliant.. Parece ser el módulo BigData de MySQL.
https://www.percona.com/software/mysql-database/percona-server/feature-comparison

Saludos

**Comment by j-lml** [comment]
¿en serio te preocupa que sea ACID? ¿cuál?

* atómico
* consistencia (=integridad)
* aislamiento (=transacciones)
* durabilidad

**Comment by moon155** [comment]
1. pues hombre, si el asunto es tener cuentas precisas...

**Comment by j-lml** [comment]
eso digo, jeje, que precisión no lo veo como problema ACID ;-)
Tenemos que conseguir que las cuentas (o el resto de datos), sean exactos o al menos conocer su calidad:
totalmente verificado, parece buena, necesita un repaso, dato horrible a arreglar, etc...

Y en las diferentes iteraciones ir mejorando, pero lo dejo que me estoy yendo de tema!

**Comment by Softman65** [comment]
de momento KAOS155  va a optar por mysql 5.7, esta testado que funciona correctamente con todos los datos cargados.

**Comment by moon155** [comment]
Ok ACID, supongo que entendeis el tema mejor que yo ;)

Y sobre MySQL, pues eso, perfecto de momento, y quizá añadir Percona algún día, que no cambia nada a los pedidos (sigue siendo MySQL).
