### ISSUE TITLE
Crowdfunding: como lo hacemos?

### ISSUE THREAD

**Issue by moon155** [Ingobernable/kaos155#16]
1. realmente queremos hacer un crowdfunding?
2. no sería un riesgo para que luego nos digan que nos financia tal o tal dictador desde la otra punto del planeta?
3. en que plataforma lo queremos hacer?
4. incluimos SM en la propuesta de crowdfunding de kaos, o hago otro aparte?
4. manifiesto para ambos!!

**Comment by j-lml** [comment]
No tengo claro ser partidario y todavía me parece que estamos lejos.
el manifiesto me parece bien

**Comment by moon155** [comment]
Yo tampoco tengo claro que sea lo mejor, pero no me veo nada lejos de poder hacerlo (si fuera buena idea), y el desarrollo iría mucho más rápido con financiación (donaciones al menos..).

**Comment by torbellina** [comment]
en realidad las personas que iniciamos el proyecto nunca tuvimos en mente hacer un crowdfunding y creemos que debemos seguir así.
 Cierro la issue pq me han explicado que github no debe de ser para estos temas sino para cosas técnicas. Sorry porque no sabíamos y hemos animado a hacerlo por aquí. ;)))
close #16

**Comment by moon155** [comment]
On 2017-11-24 21:34, torbellina wrote:
> en realidad las personas que iniciamos el proyecto nunca tuvimos en
> mente hacer un crowdfunding y creemos que debemos seguir así.

Vale, pues ya me explicareis porque, espero..

> Cierro la issue pq me han explicado que github no debe de ser para
> estos temas sino para cosas técnicas. Sorry porque no sabíamos y
> hemos animado a hacerlo por aquí. ;))) 

Me decía yo! ;)

**Comment by moon155** [comment]
Sigo este tema porque parece que no me habeis entendido.

1. No pretendo monetizar ni kaos, ni SM. Nunca he buscado curro en mi vida, y se que el día que lo haga, ganaré el doble o triple de ahora. Pero no es lo que busco, busco lo mismo que vosotros, reparar la sociedad. Pero lo veo una pena que tengamos tan poco tiempo para el proyecto (yo por lo menos), por lo que donaciones o crowdfunding eran buenas ideas en mi opinion. Y NO implican crear una empresa!!!! para nada, ni cerca. De hecho, si estuvierais para analizar riesgos y consecuencias conmigo, la mejor opción me parece que sería un monedero de bitcoins compartido entre nosotros, de tal forma que no necesitemos entidad legal (o cuenta bancaria), y que aún así, los fondos esten segurizados por todo el equipo. Enfin, que no quereis ni hablarlo, entendido.

2. Obviamente busco publicar SM con una licencia abierta. Y no una de lorem corpus que no protege nada (y desprotege todo, entonces), como habeis hecho. Pero me preocupan varias cosas (algunas de las cuales has contestado Fanta):
- que ninguna empresa coja el proyecto, lo mejore mucho a golpe de dinero e ingenieros, y empiece a derivar el objetivo (los esfuerzos, actuales y futuros) a algo "menos disruptivo", más comercial. -> parece implicar prohibir el uso comercial, o forzar difundir cualquier modificación, como apuntó Fanta.
- pero que si el proyecto algún día necesite crowfunding o algo, siendo nosotros los creadores del código, sí podamos. -> parece implicar permitir el uso comercial.
- que ninguno se atribuya la autoría de código que no haya escrito -> implica que la licencia se propague a los forks, y que las modificaciones sean declaradas como tal (un simple fork en Github me parece..). -> GPL

NO me preocupa en absoluto:
- que no gane yo dinero con SM, de hecho ahora estoy perdiendo bastante. Francamente nunca lo he visto así, y me preocupa que penseis que lo pueda ver así, por seros honesto. A mi me preocupa que tengamos poquitas horas a la semana, mientras una empresa pueda coger el código y poner varias personas a tiempo completo. Además q agota mucho pasar de un proyecto a otro todo el rato.. yo puedo seguir un mes o dos así, pero luego tendré q volver a mis proyectos (que ellos sí me permiten comer).
- que no se monetice nada del proyecto. Aunque si es para conseguir el objetivo que tenemos, tampoco me preocuparía que se monetice, a modo de sin fin de lucro obviamente, no de empresa! 

Bueno enfin, que gracias por confiar en mí, porque tenemos el mismo objetivo final. 

Y le pondre seguramente GPL2 o 3 a SM, pero sobre todo porque prefiero dejar abierta la posibilidad de hacer un crowdfunding/publicidad seria algún día, si empieza a ser obvio que puede ayudar al objetivo. Y porque dado que SM tiene dimensión mundial, espero que ninguna empresa pueda competir contra nuestra (futura) comunidad de desarrolladores. Y porque si siendo código libre se puede forzar difundir cualquier modificación al código, a lo mejor sí que protege perfectamente al proyecto. 

Oye y disculpad que no siga vuestra estrategia sin entenderla, pero ni siquiera nos conoceríamos si no fueramos tan críticos, me parece a mí ;)

**Comment by moon155** [comment]
Aclararme algo si lo sabeis por favor!

Una licencia que no permita el uso comercial, nos permitiría aún así:
A. montar una sin fin de lucro, y hacer un crowdfunding (== donaciones) para sostener costes?
B. montar una DAO y un wallet de bitcoins compartido? (para sostener costes tb)

Gracias de antemano!

**Comment by moon155** [comment]
A. a lo mejor, se resume a saber si una entidad sin animo de lucro, cuando recibe donaciones, este teniendo fines comerciales. Creo que no. Y si es así, entonces no entiendo porque quisierais permitir el uso comercial de kaos, en su licencia.
