### ISSUE TITLE
Leyenda en SCRAPEO

### ISSUE THREAD

**Issue by Softman65** [Ingobernable/kaos155#18]
Ampliación de manual
los caracteres que salen en el SCRAP tienen significado

 S = leyendo sumario .=leyendo BOLETIN +=anotando CONTRATO -=anotando NO CONTRADO  xxx = boletin fallido  fff = sumario no encontrado #=SUMARIO duplicado %=Boletín ya analizado

**Comment by ghost** [comment]
Anotado en la documentación. Cierro esto.
