### ISSUE TITLE
Procesos MULTI-HILO en node

### ISSUE THREAD

**Issue by Softman65** [Ingobernable/kaos155#21]
documentación
 http://pinchito.es/2013/modo-cluster.html

**Comment by alex-left** [comment]
anda que no ha llovido dsde entonces.. jejej

en cualquier caso, pm2 te clusteriza! 
https://pm2.keymetrics.io/docs/usage/cluster-mode/

**Comment by Softman65** [comment]
la cosa es tener control e intercambio de información entre hilos de distinta indole por ejemplo un HILO que sea la MEMORY de IA, estoy pensando en un proceso que se alimente de parser a base de unas _keys  cortitas para los nombres de empresas y de empresarios
https://www.npmjs.com/package/shorter

dotando a este modulo de operaciones mas complejas con matrices https://lodash.com/ 
y faltaría un modulo de comunicaciones para insertarla datos y hacerla consultas a las matrices en 3 4 5 millones datos a velocidad memory :)
