### ISSUE TITLE
separar ficheros sql

### ISSUE THREAD

**Issue by j-lml** [Ingobernable/kaos155#23]
propuesta de separar los ficheros sql en 3 partes diferentes:
CREATE_DB_SCRAP
DELETE_DB_SCRAP
CREATE_PROC_SCRAP

No se si afecta a algo de código, aunque entiendo que en principio no tiene que hacerlo

**Comment by j-lml** [comment]
Voy a intentar hacerlo siguiendo el procedimiento de git que recomiendan en GitHub a ver si cuadra:

* crear rama específica para la issue 
* nombrarla issue-23
* hacer pull request

[guía de estilo](https://github.com/jeko2000/git-style-guide#branches)

**Comment by j-lml** [comment]
al poner en el commit # y numero de issue automáticamente quedan relacionados

**Comment by j-lml** [comment]
Parece que todo correcto. 
Si al hacer commit  se pone en el texto descriptivo almohadilla y número de incidencia, se queda relacionado automáticamente
#23

**Comment by Softman65** [comment]
me parece regular, mas coñazo de mantenimiento, además no pierdas de vista
que la aplicación crea sola la DB con 1 solo papelote.

2017-12-01 17:14 GMT+01:00 j-lml <notifications@github.com>:

**Comment by Softman65** [comment]
habría que cambiar la linea 100 de https://github.com/Ingobernable/kaos155/blob/master/App/node_app/sql_common.js

donde dice:                                                     
cp.exec('mysql -u' + resp.user + ' -p' + resp.password + ' -h' + resp.host + ' < ' + app.path.normalize('sqlfiles/CREATE_DB_' + options.Command + '.sql'), (error, stdout, stderr) => {

deberia decir:
                                                    cp.exec('mysql -u' + resp.user + ' -p' + resp.password + ' -h' + resp.host + ' < ' + app.path.normalize('sqlfiles/CREATE_FULL_' + options.Command + '.sql'), (error, stdout, stderr) => {
