### ISSUE TITLE
reorganizar ramas

### ISSUE THREAD

**Issue by j-lml** [Ingobernable/kaos155#25]
varias incidencias con respecto a los commit:
* estamos trabajando normalmente contra master
* las ramas se quedan muertas de risa
* development siempre se queda desactualizado cuando debe ser la de trabajo

propuesta de soluciones:
* borrar rama `development` (normalmente esta rama se conoce como `dev`)
* crear rama con nombre `dev`
* modificar en github para que `dev` sea rama por defecto! (ayudará a que cojamos costumbre de trabajar contra `dev`

siguiente nivel:
* NO aceptar peticiones Pull Request que vayan contra `master`. Se rechaza y se pide que se haga el pull request a `dev`.
* Eliminar las ramas en las que YA no se esté trabajando. A no ser que tengan información importante (sacado de la documentación de [GitHub](https://guides.github.com/features/issues/))

**Comment by j-lml** [comment]
en `settings / branches` se puede poner dos confiraciones:
* branch por defecto (`dev`)
* proteger branch (`master`)

**Comment by Softman65** [comment]
ha intentado reorganizar todo, al proteger el master, me salen muchas opciones que no se exactamente cuales escoger
